#Load data and libraries
```{r}
gsva.es <- readRDS("/Users/paulaverdung/Desktop/Uni/Bachelor MoBi/Info/Bioinfoprojekt/gsva_es_comb.RDS")

library(leaps)
library(ggplot2)
library(pheatmap)
```


#Filter data to top 50 most variable genes
```{r}
data_lin <- gsva.es[order(apply(gsva.es, 1, var))[1:50], ]
```

#Check correlation of filtered dataset
```{r}
#Correlation matrix
correlation_matrix <- cor(t(data_lin))
corr_heatmap <- pheatmap(correlation_matrix, cluster_rows = F, cluster_cols = F)
```


#Split data into training and test sets
```{r}
regression_data_lin <- as.data.frame(t(data_lin))

set.seed(123)
nsample <- sample.int(n = nrow(regression_data_lin), size = floor(.8*nrow(regression_data_lin)), replace = F)
train_lin <- regression_data_lin[nsample, ]
test_lin <- regression_data_lin[-nsample, ]
```

#Find best model 
```{r}
best_subset <- regsubsets(HALLMARK_KRAS_SIGNALING_DN ~ ., data = train_lin, method = "exhaustive")
summary_best_lm <- summary(best_subset)

#determining best model from results
pred_nr <- which.max(summary_best_lm$adjr2)   #Number of predictors
names_pred <- names(summary_best_lm$which[pred_nr, ][which(summary_best_lm$which[pred_nr, ])])
```

#Create linear model based on predictors determined prior
```{r}
formula_lm2 = formula(paste("HALLMARK_KRAS_SIGNALING_DN", "~", paste(names_pred[-1], collapse=" + ")))
best_lm <- lm(formula_lm2, data = train_lin)
```

#Plot predicted values against reference
```{r}
reference_lm <- test_lin$HALLMARK_KRAS_SIGNALING_DN
prediction_lm <- predict(best_lm, test_lin)
lm_df <- data.frame(reference_lm, prediction_lm)

lm_plot <- ggplot(lm_df, aes(x = reference_lm, y = prediction_lm)) + geom_point() + geom_abline(intercept = 0, slope = 1, color = "red", linewidth = 1)  + ggtitle("Predicted vs. Reference values")
```


