---
output:
  html_document: default
  pdf_document: default
---
# Introduction

## Cancer

Cancer is a disease characterized by the uncontrolled growth and spread of cells from various origins due to damage in critical genetic programs. These genetic alterations lead to the development of specific biological features, known as cancer hallmarks. The hallmarks of cancer include capabilities such as sustaining proliferative signaling and genome instability [@OldHallmarks]. Recent discoveries have expanded these hallmarks to include properties resulting from the tumor microenvironment, which consists of both cancerous and ostensibly healthy cells, such as macrophages. Today the new and established hallmarks are consolidated in the updated list of cancer hallmarks [@Hallmarks].\newline
Cancer is the second leading cause of death worldwide, accounting for 10 million deaths annually, with 1.9 million new cases emerging each year in the US alone (a trend that is increasing) [@CancerStatistics]. Thus, identifying and characterizing new targets for cancer detection and treatment is crucial to reducing its lethality.

## LUAD

LUAD is a type of non-small-cell lung cancer and yet remains the most common primary lung cancer, accounting for 40% of lung cancers. Due to late diagnoses in middle and late stages, LUAD has a 5-year survival rate of only 12-15%. This low survival rate, combined with the high number of cases, makes LUAD the leading cause of cancer-related deaths in the US, with 158,000 deaths in 2015.\newline
LUAD is often associated with perturbations and deregulation of specific pathways and genes, such as the mitogen-activated protein kinase (MAPK) pathway (involved in cell survival and proliferation), the tumor suppressor gene P53, and the epithelial growth factor receptor (EGFR), among others [@MutationsLUAD]. Identifying these perturbations and dysregulations is essential for diagnosing LUAD. Moreover, developing and improving therapy options are key to reducing deaths caused by LUAD [@CancerStatistics].

## LUAD vs. LUSC 

To effectively tackle cancer and choose the right therapeutic approach for each patient, it is essential to fully differentiate between closely related cancer types, such as LUAD and LUSC. Historically, these two tumor types were categorized by their histology and grouped together as non-small-cell lung cancer (NSCLC). However, recent studies suggest that differentiating between the two and providing tailored treatment can increase therapeutic success. Therefore, it is crucial to identify and characterize the differences between LUAD and LUSC to distinguish them accurately, for instance, by visualizing and analyzing differences and similarities in expression data [@LUADvsLUSC1].