## UMAP auf GSVA

```{r}
library(umap)
library(ggplot2)

# transpose matrix
gsva_t <- t(gsva_es_comb)
```

```{r}
# calculate umap
umap_gsva <- umap(gsva_t)

# check dimension
print(dim(umap_gsva$layout))  # should be n x 2 
```

```{r}
plot(umap_gsva$layout[,1], umap_gsva$layout[,2],
     xlab = "UMAP Dimension 1", ylab = "UMAP Dimension 2",
     main = "UMAP Plot",
     pch = 20)
```

```{r}
# combine data
umap_gsva <- data.frame(
  UMAP1 = umap_gsva$layout[, 1],
  UMAP2 = umap_gsva$layout[, 2],
  tumor = tcga_annot$cancer_type_abbreviation
)

# plot umap results
ggplot(umap_gsva, aes(x = UMAP1, y = UMAP2, color = tumor)) +
  geom_point(size = 0.3) +
  labs(title = "UMAP plot colored according to tumor types",
       x = "UMAP dimension 1",
       y = "UMAP dimension 2") +
  theme_minimal() +
  theme(legend.position = "right")  
```

```{r}
# combine data
umap_gsva <- data.frame(
  UMAP1 = umap_gsva$layout[, 1],
  UMAP2 = umap_gsva$layout[, 2],
  tumor = tcga_annot$cancer_type_abbreviation
)

# define colors
unique_tumortypen <- unique(umap_gsva$tumor)
default_colors <- setNames(scales::hue_pal()(length(unique_tumortypen) - 1), unique_tumortypen[unique_tumortypen != "LUAD"])
tumortyp_colors <- c(default_colors, LUAD = "black")

# plot umap
ggplot(umap_gsva, aes(x = UMAP1, y = UMAP2, color = tumor)) +
  geom_point(size = 0.3) +
  labs(title = "UMAP plot colored according to tumor types",
       x = "UMAP dimension 1",
       y = "UMAP dimension 2") +
  scale_color_manual(values = tumortyp_colors) +
  theme_minimal() +
  theme(legend.position = "right")
```

```{r}
# combine data
umap_gsva <- data.frame(
  UMAP1 = umap_gsva$layout[, 1],
  UMAP2 = umap_gsva$layout[, 2],
  Tumortypen = tcga_annot$cancer_type_abbreviation
)

# define colors
unique_tumortypen <- unique(umap_gsva$Tumortypen)
default_colors <- setNames(scales::hue_pal()(length(unique_tumortypen) - 2), unique_tumortypen[!unique_tumortypen %in% c("COAD", "READ")])
tumortyp_colors <- c(default_colors, COAD = "black", READ = "red")  # LUAD in schwarz und LUSC in rot

# plot umap
ggplot(umap_gsva, aes(x = UMAP1, y = UMAP2, color = Tumortypen)) +
  geom_point(size = 0.3) +
  labs(title = "UMAP Plot nach Tumortypen",
       x = "UMAP Dimension 1",
       y = "UMAP Dimension 2") +
  scale_color_manual(values = tumortyp_colors) +
  theme_minimal() +
  theme(legend.position = "right")

```


## Features plot auf GSVA UMAP Daten 
```{r}
gsva_es_comb_t <- t(gsva_es_comb)

# extract enrichment scores of special genesets / pathways
scores <- gsva_es_comb
scores <- t(scores)
MYC_UP.V1_UP <- scores[, 62]

# plot umap results
ggplot(umap_gsva, aes(x = UMAP1, y = UMAP2, color = MYC_UP.V1_UP)) +
  geom_point(size = 0.3) +
  labs(title = "UMAP Plot: Myc",
       x = "UMAP Dimension 1",
       y = "UMAP Dimension 2") +
  scale_color_gradient(low = "dodgerblue", high = "brown1", name = "enrichment") +
  theme_minimal() +
  theme(legend.position = "right")  

```

```{r}
gsva_es_comb_t <- t(gsva_es_comb)

# extract enrichment scores of special genesets / pathways
scores <- gsva_es_comb
scores <- t(scores)
HALLMARK_COAGULATION <- scores[, 10]

# plot umap results
ggplot(umap_gsva, aes(x = UMAP1, y = UMAP2, color = HALLMARK_COAGULATION)) +
  geom_point(size = 0.3) +
  labs(title = "UMAP Plot: Coagulation",
       x = "UMAP Dimension 1",
       y = "UMAP Dimension 2") +
  scale_color_gradient(low = "dodgerblue", high = "brown1", name = "enrichment") +
  theme_minimal() +
  theme(legend.position = "right")  
```


```{r}
gsva_es_comb_t <- t(gsva_es_comb)

# extract enrichment scores of special genesets / pathways
scores <- gsva_es_comb
scores <- t(scores)
HALLMARK_PI3K_AKT_MTOR_SIGNALING <- scores[, 39]


# plot results
ggplot(umap_gsva, aes(x = UMAP1, y = UMAP2, color = HALLMARK_PI3K_AKT_MTOR_SIGNALING)) +
  geom_point(size = 0.3) +
  labs(title = "UMAP Plot: PI3K-Akt-mTOR signaling",
       x = "UMAP Dimension 1",
       y = "UMAP Dimension 2") +
  scale_color_gradient(low = "dodgerblue", high = "brown1", name = "enrichment") +
  theme_minimal() +
  theme(legend.position = "right")  

```

```{r}
gsva_es_comb_t <- t(gsva_es_comb)

# extract enrichment scores of special genesets / pathways
scores <- gsva_es_comb
scores <- t(scores)
HALLMARK_OXIDATIVE_PHOSPHORYLATION <- scores[, 36]


# plot results
ggplot(umap_gsva, aes(x = UMAP1, y = UMAP2, color = HALLMARK_OXIDATIVE_PHOSPHORYLATION)) +
  geom_point(size = 0.3) +
  labs(title = "UMAP Plot: oxidative phosphorylation",
       x = "UMAP Dimension 1",
       y = "UMAP Dimension 2") +
  scale_color_gradient(low = "dodgerblue1", high = "brown1", name = "enrichment") +
  theme_minimal() +
  theme(legend.position = "right")  

```

