Filtering LUAD-tumor data set according to protein-coding genes 
```{r}
library(biomaRt)
library(AnnotationDbi)

mart <- useMart("ensembl")
ensembl = useMart("ensembl", dataset = "hsapiens_gene_ensembl")

#list of all human genes and their attributes 
genes = getBM(attributes = c("ensembl_gene_id", "gene_biotype"), mart = ensembl)

# extracte protein-coding genes
protein_coding_genes = subset(genes, gene_biotype == "protein_coding")

# attention --> this code inserts only an empty column at the end oft the dara record 
luad.tumor$ensembl_gene_id = sub("\\..*", "", rownames(luad.tumor))

# Filtering  
luad.tumor_filtered_proteins <- luad.tumor[luad.tumor$ensembl_gene_id %in% protein_coding_genes$ensembl_gene_id, ]

# rownames are overwritten with gene IDs 
rownames(luad.tumor_filtered_proteins) <- luad.tumor_filtered_proteins[, ncol(luad.tumor_filtered_proteins)]

# remove last column 
luad.tumor_filtered_proteins <- luad.tumor_filtered_proteins[, -ncol(luad.tumor_filtered_proteins)]

# checking dimensions
dim(luad.tumor)
dim(luad.tumor_filtered_proteins)
```


Filtering LUAD-norm data set according to protein-coding genes 
```{r}
library(biomaRt)
library(AnnotationDbi)

mart <- useMart("ensembl")
ensembl = useMart("ensembl", dataset = "hsapiens_gene_ensembl")

# list of all human genes and their attributes 
genes = getBM(attributes = c("ensembl_gene_id", "gene_biotype"), mart = ensembl)

# extracte protein-coding genes
protein_coding_genes = subset(genes, gene_biotype == "protein_coding")

# attention --> this code inserts only an empty column at the end oft the dara record 
luad.norm$ensembl_gene_id = sub("\\..*", "", rownames(luad.norm))

# Filtering
luad.norm_filtered_proteins <- luad.norm[luad.norm$ensembl_gene_id %in% protein_coding_genes$ensembl_gene_id, ]

# rownames are overwritten with gene IDs 
rownames(luad.norm_filtered_proteins) <- luad.norm_filtered_proteins[, ncol(luad.norm_filtered_proteins)]

# remove last column
luad.norm_filtered_proteins <- luad.norm_filtered_proteins[, -ncol(luad.norm_filtered_proteins)]

# checking dimensions 
dim(luad.norm)
dim(luad.norm_filtered_proteins)
```

# visualisation of cancer data of LUAD patients 
```{r}
library(ggplot2)
# transposing matrix 
luad.tumor_filtered_proteins_t <- t(luad.tumor_filtered_proteins)
```

```{r}
# applying UMAP on filtered cancer data 
umap_luad.tumor_filtered_proteins_t  <- umap(luad.tumor_filtered_proteins_t )

# checking dimensio of umap results
print(dim(umap_luad.tumor_filtered_proteins_t $layout))  # should be n x 2  (n = number of data points)
```

```{r}
# plotting results of umap 
plot(umap_luad.tumor_filtered_proteins_t $layout[,1], umap_luad.tumor_filtered_proteins_t $layout[,2],
     xlab = "UMAP Dimension 1", ylab = "UMAP Dimension 2",
     main = "UMAP Plot", pch = 20)
```

```{r}
# combine data of umap with clinical annotations
umap_data <- data.frame(
  UMAP1 = umap_luad.tumor_filtered_proteins_t $layout[, 1],
  UMAP2 = umap_luad.tumor_filtered_proteins_t $layout[, 2],
  Tumorstage = luad.annot$ajcc_pathologic_tumor_stage
)

# create UMAP-Plot (colored tumorstages)
ggplot(umap_data, aes(x = UMAP1, y = UMAP2, color = Tumorstage)) +
  geom_point(size = 2) +
  labs(title = "UMAP Plot with colored tumorstages",
       x = "UMAP Dimension 1",
       y = "UMAP Dimension 2") +
  theme_minimal() +
  theme(legend.position = "right")
````
